---
- name: Join worker nodes to k3s cluster
  hosts: nodes
  become: yes
  vars:
    k3s_url: "https://{{ K8S_MASTER_IP }}:6443"
    k3s_token: "{{ K3S_TOKEN }}"

  tasks:
    - name: Disable swap immediately
      shell: swapoff -a
      ignore_errors: true
      changed_when: false

    - name: Remove swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^\s*(\S+\s+\S+\s+swap\s+\S+.*)$'
        replace: '# \1'

    - name: Wait for apt lock to be released
      shell: |
        timeout=60
        while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for apt lock..."
          sleep 3
          timeout=$((timeout - 3))
          if [ "$timeout" -le 0 ]; then
            echo "Timeout reached."
            exit 1
          fi
        done
      changed_when: false

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install Docker 
      apt:
        name: docker.io
        state: present

    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service

    - name: Re-install k3s-agent if node not in cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -

    - name: Restart k3s-agent
      systemd:
        name: k3s-agent
        state: restarted